### ISSUE TITLE
what does this do

### ISSUE THREAD

**Issue by yeet-dot-org** [TheLastGimbus/the_last_bluetooth#1]
read title

on an unrelated note,  i have send you 3$ for the very useful google photos meta data fixer, thank you. i did notice the album shortcuts are set to the root of the c:/ drive, a bit weird. and the finished folder is smaller at 27.1gb vs the 29.7gb zip file.
(maybe i should've send this in the google photos metadata repo actually)

**Comment by TheLastGimbus** [comment]
Hi!

This is my Bluetooth classic flutter library, internally used in FreeBuddy - it's not well tested or documented yet, that's why it's not on pub

All things about gpth please describe widely on the repo there, i will try to help
